name: Release

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        run: |
          sudo apt install ruby-full=1:2.7+1
          sudo gem install bundler:2.2
          bundle _2.2.0_ install
          sudo apt update
      - name: Release Gem
        uses: discourse/publish-rubygems-action@v2-beta
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          RELEASE_COMMAND: bin/release
          GIT_EMAIL: support@veryfi.com
          GIT_NAME: Github Action
